name: Android Build

on:
  pull_request:
    branches: [ master ]

  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: "oracle"

      - name: Setup Gradle
        #uses: gradle/gradle-build-action@v3.5.0
        uses: gradle/actions/setup-gradle@v3.5.0
        with:
            gradle-version: 8.4

      - name: Check gradle version
        run: gradle --version

      - name: Build with Gradle
        #run: ./gradlew build
        run: gradle build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: GraphqlApp.apk
          path: app/build/outputs/apk/app-debug.apk
